title = "Create 100k canisters"
description = "Stress creation and scheduling of 100k canisters"

[[workload]]
canister = "counter"
duration = 300
rps = 1

[[workload]]
canister = "canister-creator-canister#1"
duration = 1
rps = 1
call_method = "create_canisters"
method = "Update"
json_payload = '10000'

[[workload]]
canister = "canister-creator-canister#2"
duration = 1
rps = 1
call_method = "create_canisters"
method = "Update"
json_payload = '10000'

[[workload]]
canister = "canister-creator-canister#3"
duration = 1
rps = 1
call_method = "create_canisters"
method = "Update"
json_payload = '10000'

[[workload]]
canister = "canister-creator-canister#4"
duration = 1
rps = 1
call_method = "create_canisters"
method = "Update"
json_payload = '10000'

[[workload]]
canister = "canister-creator-canister#5"
duration = 1
rps = 1
call_method = "create_canisters"
method = "Update"
json_payload = '10000'

[[workload]]
canister = "canister-creator-canister#6"
duration = 1
rps = 1
call_method = "create_canisters"
method = "Update"
json_payload = '10000'

[[workload]]
canister = "canister-creator-canister#7"
duration = 1
rps = 1
call_method = "create_canisters"
method = "Update"
json_payload = '10000'

[[workload]]
canister = "canister-creator-canister#8"
duration = 1
rps = 1
call_method = "create_canisters"
method = "Update"
json_payload = '10000'

[[workload]]
canister = "canister-creator-canister#9"
duration = 1
rps = 1
call_method = "create_canisters"
method = "Update"
json_payload = '10000'

[[workload]]
canister = "canister-creator-canister#10"
duration = 1
rps = 1
call_method = "create_canisters"
method = "Update"
json_payload = '10000'
