title = "Benchmark heap performance"
description = "Initially read only, later with a very low write-ratio."

# Deploy testnet to benchmark with shorter dkg interval length
# testnet/tools/icos_deploy.sh --git-revision $(./gitlab-ci/src/artifacts/newest_sha_with_disk_image.sh origin/master) $TESTNET --dkg-interval-length 100

[[workload]]
canister = "heap#1"
duration = 300
rps_ratio = 1
call_method = "query_read_fwd_1gb"
method = "Query"

[[workload]]
canister = "heap#2"
# Dirty pages to generate heap delta. The query latency should be increased during this time.
start_delay = 100
duration = 100
rps = 0.02 # One request every 5s
call_method = "update_write_bwd_1gb_step_4kb"
method = "Update"
