title = "Registry canister"
description = "Benchmark the registry canister"

[[workload]]
canister = "registry"
call_method = "get_build_metadata"  # Could also use "get_changes_since", but need pb arg then
method = "Update"  # Replicated queyr call
raw_payload = "4449444c0000"  # get_build_metadata expect Candid payload

# Alternatively: can also do "get_latest_version" with empty payload

# didc encode '()'
# 4449444c0000