title = "Motoko sha256 workload"
description = "Motoko's sha256 benchmark from: https://github.com/dfinity/motoko/blob/master/test/perf/sha256.mo"

[[workload]]
canister = "sha256"
raw_payload = "4449444C0000"
method = "Update"
call_method = "go"

# https://fxa77-fiaaa-aaaae-aaana-cai.raw.ic0.app/explain shows
#
# 44 49 44 4c: magic header
# 00: type table of size 0
# 00: arg count of 0